SCRAPERWIKI_URL = 'https://free-ec2.scraperwiki.com'
SCRAPERWIKI_PUBLISH_TOKEN = 'fb1171f4-4d77-479c-96a2-685b705702b3'
SCRAPERWIKI_BOX_NAME = 'gjv26pi'
SCRAPERWIKI_SQL_API = '%s/%s/%s/sql?q=' % (
    SCRAPERWIKI_URL,
    SCRAPERWIKI_BOX_NAME,
    SCRAPERWIKI_PUBLISH_TOKEN
)

CAPEMETRO_URL = 'http://www.capemetrorail.co.za/_timetables'

SITE_ROOT = '%s/%s/%s/http/' % (
    SCRAPERWIKI_URL,
    SCRAPERWIKI_BOX_NAME,
    SCRAPERWIKI_PUBLISH_TOKEN
)
